### ISSUE TITLE
@sensenet/redux type safety improvements

### ISSUE THREAD

**Issue by gallayl** [SenseNet/sn-redux#98]
### Problem:
The current store implementation doesn't have exlicit Redux types, we should define explicit types for all actions and reducers.
#### Example for Action:
```ts
export const userLogout = () => ({
    type: 'USER_LOGOUT',
    // tslint:disable:completed-docs
    async payload(repository) {
        const response = await repository.authentication.logout()
        return response
    },
})
```
should be:
```ts
export const userLogout: 
    Action & { payload: (repository: Repository) => Promise<boolean> } = () => ({
    type: 'USER_LOGOUT',
    async payload(repository: Repository) {
        const response = await repository.authentication.logout()
        return response
    },
})
```

#### Example for reducer:
```ts
export const country = (state = '', action) => {
    return state
}
```
should be
```ts
export const country: Reducer<string, Action> = (state = '', action: Action) => {
    return state
}
```

Reducer helper methods should be also extended with type info.

#### Tasks
 - [x] Enable strict mode & strict null checks in tsconfig
 - [x] Fix the missing type declarations
 - [x] Review 3rd party components (e.g. [normalizr](https://github.com/paularmstrong/normalizr/issues/326)) typescript compatibility
 - [x] Review the **sensenet** state structure. There should'nt be 'any' leafs left in the store
